version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:16.13.2
  node_with_postgres:
    docker:
      - image: cimg/node:16.13.2
        environment:
          NODE_ENV: test
          POSTGRES_DATABASE: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          SERVER_PORT: 3001
      - image: cimg/postgres:13.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

jobs:
  run_tests:
    executor: node_with_postgres
    steps:
      - checkout
      - run:
          name: Run tests
          command: npx lerna run test:ci --stream

  build_packages:
    executor: node
    steps:
      - checkout
      - run:
          name: Build packages
          command: npx lerna run build --stream

workflows:
  countinuous_integration:
    jobs:
      - run_tests
      - build_packages
